### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [Dario-Cabrera/Backend-Medical_Rolling#37]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/Dario-Cabrera/Backend-Medical_Rolling/assets/166792979/184d4748-fdec-4f9f-a42a-a9b8aada3ed9)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Dario-Cabrera** [comment]
Estimado, buenas tardes!

Perfecto, ahora vamos a eliminar todos los cambios y código comentado en el
proyecto, además de eso detecto alguna otra mejora a realizar?

No lo encontré en el slack para enviarle por ese medio.

Gracias desde ya.

Saludos!
